name: build-workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Java
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'oracle'
      - name: Build
        run: make -C app build
